repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo Format
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: cargo-clippy
        name: Cargo Clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: cargo-test
        name: Cargo Test
        entry: cargo test --all-features
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: cargo-check
        name: Cargo Check
        entry: cargo check --all-features
        language: system
        types: [rust]
        pass_filenames: false