edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"
merge_derives = true
use_small_heuristics = "Default"
format_code_in_doc_comments = true
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0