name: Feature Request
description: Suggest a new feature for the JPEG XS implementation
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or use case this feature would solve
      placeholder: I'm trying to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: The feature should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: Other approaches...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request